<?php

namespace AppBundle\Repository;

/**
 * AnnonceAppartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceAppartementRepository extends \Doctrine\ORM\EntityRepository
{
}
