<?php

namespace AppBundle\Repository;

/**
 * AnnonceBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceBienRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * calcul du nombre de bien
     */
    public function cpteur($typebien)
    {
        return $this->createQueryBuilder('b')
                    ->select('count(b.id)')
                    ->where('b.typebien = :bien')
                    ->setParameter('bien', $typebien)
                    ->getQuery()->getSingleScalarResult()
            ;
    }

    public function findBien($bien)
    {
        return $this->createQueryBuilder('b')
                    ->where('b.slug = :bien')
                    ->setParameter('bien', $bien)
        ;
    }

    /**
     * Liste des annonces par ordre decroissant
     */
    public function findListAnnonce($user)
    {
        return $this->createQueryBuilder('b')
                    ->where('b.utilisateur = :user')
                    ->orderBy('b.id', 'DESC')
                    ->setParameter('user', $user)
                    ->getQuery()->getResult()
        ;
    }

    /**
     * Liste decroissante des annonces
     * Utiliser par frontendController/AnnonceAction
     */
    public function findListDesc(){
        return $this->createQueryBuilder('b')
                    ->where('b.fille = 1')
                    ->andWhere('b.statut = 1')
                    ->orderBy('b.id', 'DESC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste des biens annonces
     */
    public function findListBien($limit = null, $offset = null)
    {
        if ($limit){
            return $this->createQueryBuilder('b')
                ->orderBy('b.id', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults($limit)
                ->getQuery()->getResult()
                ;
        }else{
            return $this->createQueryBuilder('b')->orderBy('b.id', 'DESC')->getQuery()->getResult();
        }
    }
}
