<?php

namespace AppBundle\Repository;

/**
 * AnnonceImmeubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceImmeubleRepository extends \Doctrine\ORM\EntityRepository
{
}
