<?php

namespace AppBundle\Repository;

/**
 * AnnonceVillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceVillaRepository extends \Doctrine\ORM\EntityRepository
{
}
