<?php

namespace AppBundle\Repository;

/**
 * AnnonceBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceBienRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBien($bien)
    {
        return $this->createQueryBuilder('b')
                    ->where('b.slug = :bien')
                    ->setParameter('bien', $bien)
        ;
    }

    /**
     * Liste des annonces par ordre decroissant
     */
    public function findListAnnonce($user)
    {
        return $this->createQueryBuilder('b')
                    ->where('b.utilisateur = :user')
                    ->orderBy('b.id', 'DESC')
                    ->setParameter('user', $user)
                    ->getQuery()->getResult()
        ;
    }
}
