<?php

namespace AppBundle\Repository;

/**
 * AnnonceAutrebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceAutrebienRepository extends \Doctrine\ORM\EntityRepository
{
}
