<?php

namespace AppBundle\Repository;

/**
 * AppartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartementRepository extends \Doctrine\ORM\EntityRepository
{
}
