<?php

namespace AppBundle\Repository;

/**
 * AppartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartementRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * Recherche des appartements
    */
    public function findAppartement($typebien, $whereZone, $whereMin, $whereMax, $wherePiece, $localisation, $mode, $min, $max, $nbPiece)
    { //die($mode);
        return $this->createQueryBuilder('a')
            ->addSelect('b')
            ->addSelect('z')
            ->addSelect('m')
            ->innerJoin('a.bien', 'b')
            ->innerJoin('b.typebien', 't')
            ->innerJoin('b.zone', 'z')
            ->innerJoin('b.mode', 'm')
            ->where('t.libelle = :typebien')
            ->andWhere($whereZone)
            ->andWhere($whereMin)
            ->andWhere($whereMax)
            ->andWhere($wherePiece)
            ->andWhere('m.libelle = :mode')
            ->orderBy('b.flag', 'DESC')
            ->setParameters(array(
                'typebien'  => $typebien,
                'localite'  => $localisation,
                'min'       => $min,
                'max'       => $max,
                'piece'     => $nbPiece,
                'mode'      => $mode,
            ))
            ->getQuery()->getResult()
            ;
    }
}
