<?php

namespace AppBundle\Repository;

/**
 * AutrebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutrebienRepository extends \Doctrine\ORM\EntityRepository
{
}
