<?php

namespace AppBundle\Repository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Recherche du bien par son ID pour AutrebienType.php
     */
    public function findBien($bien)
    {
        return $q = $this->createQueryBuilder('b')
                         ->where('b.id = :id')
                         ->setParameter('id', $bien)
            ;
    }

    /**
     * Liste des bien par ordre decroissant
     */
    public function findAllDesc()
    {
        return $q = $this->createQueryBuilder('b')
                         ->orderBy('b.id', 'DESC')
                         ->getQuery()->getResult()
            ;
    }

    /**
     * Liste d'un certains nombres de bien
     */
    public function findListBien($offset, $limit)
    {
        return $q = $this->QueryBien()
                         ->setFirstResult($offset)
                         ->setMaxResults($limit)
                         ->getQuery()->getResult()
            ;
    }

    /**
     * Bien en publicité
     */
    public function findBienEnPromo($offset, $limit)
    {
        return $q = $this->createQueryBuilder('b')
                         ->where('b.datedebut <= :date')
                         ->andWhere('b.datefin >= :date')
                         ->orderBy('b.datedebut', 'ASC')
                         ->setFirstResult($offset)
                         ->setMaxResults($limit)
                         ->setParameters(array(
                             'date' => date('Y-m-d', time())
                         ))
                         ->getQuery()->getResult()
            ;
    }

    /**
     * fonction de recherche
     */
    public function QueryBien()
    {
        return $q = $this->createQueryBuilder('b')
                         ->orderBy('b.id', 'DESC')
            ;
    }
}
