<?php

namespace AppBundle\Repository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des domaines par ordre alphabetiques
     */
    public function getListeAsc()
    {
        return $this->createQueryBuilder('d')
                    ->orderBy('d.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
