<?php

namespace AppBundle\Repository;

/**
 * GallerieAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GallerieAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
