<?php

namespace AppBundle\Repository;

/**
 * GalleriebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleriebienRepository extends \Doctrine\ORM\EntityRepository
{
}
