<?php

namespace AppBundle\Repository;

/**
 * ModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste des modes par ordre alphabetique
     */
    public function getListeAsc()
    {
        return $this->createQueryBuilder('m')
                    ->orderBy('m.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
