<?php

namespace AppBundle\Repository;

/**
 * MouchardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouchardRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Calcul du nombre de mouchard non lus
     */
    public function findNonLu()
    {
        return $this->createQueryBuilder('m')
                    ->select('count(m.id)')
                    ->where('m.flag IS NULL')
                    ->getQuery()->getSingleScalarResult()
            ;
    }

    /**
     * Liste des mouchards
     */
    public function findList()
    {
        return $this->createQueryBuilder('m')
                    ->orderBy('m.flag', 'ASC')
                    ->addOrderBy('m.createdAt', 'DESC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste des derniers mouchards
     */
    public function findLast($limit)
    {
        return $this->createQueryBuilder('m')
                    ->orderBy('m.createdAt', 'DESC')
                    ->setFirstResult(0)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }
}
