<?php

namespace AppBundle\Repository;

/**
 * PartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des partenaires par ordre alphabetiques
     */
    public function getListeAsc()
    {
        return $this->createQueryBuilder('p')
                    ->orderBy('p.nom', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
