<?php

namespace AppBundle\Repository;

/**
 * PartenaireCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireCompteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Verification d'existence de partenaire
     */
    public function verif($partenaire)
    {
        return $this->createQueryBuilder('pc')
                    ->where('pc.partenaire LIKE :partenaire')
                    ->setParameter('partenaire', '%'.$partenaire.'%')
                    ->getQuery()->getResult()
            ;
    }
}
