<?php

namespace AppBundle\Repository;

/**
 * PartenaireCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaireCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
