<?php

namespace AppBundle\Repository;

/**
 * PubliciteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubliciteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * La publicite en cours
     */
    public function findPubliciteEncours($offset = null, $limit = null)
    {
        return $q = $this->createQueryBuilder('p')
                         ->where('p.statut = 1')
                         ->andWhere('p.datedebut <= :date')
                         ->andWhere('p.datefin >= :date')
                         ->andWhere('p.heuredeb <= :heure')
                         ->andWhere('p.heurefin >= :heure')
                         ->andWhere('p.statut = 1')
                         ->setFirstResult($offset)
                         ->setMaxResults($limit)
                         ->setParameters(array(
                             'date' => date('Y-m-d', time()),
                             'heure' => date('H:i', time())
                         ))
                         ->getQuery()->getResult()
            ;
    }
}
