<?php

namespace AppBundle\Repository;

/**
 * RubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des rubriques par ordre alphabetique
     */
    public function getListeAsc()
    {
        return $this->createQueryBuilder('r')
                    ->orderBy('r.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
