<?php

namespace AppBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste des services par ordre alphabetique
     */
    public function getListeAsc()
    {
        return $this->createQueryBuilder('s')
                    ->orderBy('s.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
