<?php

namespace AppBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste des services par ordre alphabetique
     */
    public function getListeAsc()
    {
        return $this->createQueryBuilder('s')
                    ->orderBy('s.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Calcul du nombre de partenaire concernés par le service
     */
    public function cpteurPartenaire($service)
    {
        return $q = $this->createQueryBuilder('s')
                        ->select('count(p.id)')
                        ->innerJoin('s.partenaires', 'p')
                        ->where('s.id = :service')
                        ->andWhere('p.statut = 1')
                        ->setParameter('service', $service)
                        ->getQuery()->getSingleScalarResult();
            ;
    }

    /**
     * Calcul du nombre de partenaire concernés par le service
     */
    public function cpteurDomainePartenaire($domaine)
    {
        return $q = $this->createQueryBuilder('s')
            ->select('count(p.id)')
            ->innerJoin('s.partenaires', 'p')
            ->where('s.domaine = :domaine')
            ->andWhere('p.statut = 1')
            ->setParameter('domaine', $domaine)
            ->getQuery()->getSingleScalarResult();
        ;
    }

    /**
     * Liste des services selon le domaine
     */
    public function findListeServiceBy($domaine)
    {
        return $this->createQueryBuilder('s')
                    ->innerJoin('s.domaine', 'd')
                    ->where('d.slug = :domaine')
                    ->orderBy('s.libelle', 'ASC')
                    ->setParameter('domaine', $domaine)
                    ->getQuery()->getResult();
            ;
    }
}
