<?php

namespace AppBundle\Repository;

/**
 * TypebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypebienRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste des type de bien par order alphabetique
     */
    public function getListeAsc(){
        return $this->createQueryBuilder('t')
                    ->orderBy('t.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste des types de bien sauf cuisine et porte & fenetre
     * function utilisée dans recherche principale (rfrontend_principale)
     */
    public function findList()
    {
        return $this->createQueryBuilder('t')
                    //->where('t.slug <> :slug1')
                    //->andWhere('t.slug <> :slug2')
                    ->andWhere('t.statut = 1')
                    ->orderBy('t.libelle', 'ASC')
                    /*->setParameters([
                        'slug1' => 'cuisine',
                        'slug2' => 'porte-fenetre'
                    ])*/
                    ->getQuery()->getResult()
            ;
    }
}
