<?php

namespace AppBundle\Repository;

/**
 * TypebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypebienRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Liste des type de bien par order alphabetique
     */
    public function getListeAsc(){
        return $this->createQueryBuilder('t')
                    ->orderBy('t.libelle', 'ASC')
                    ->getQuery()->getResult()
            ;
    }
}
