<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUtilisateur($user)
    {
        return $this->createQueryBuilder('u')
                    ->where('u.id = :id')
                    ->setParameter('id', $user)
        ;
    }

    /**
     * Nombre d'utilisateur
     * use DefaultController:backendAction
     */
    public function cptUser()
    {
        return $this->createQueryBuilder('u')
                    ->select('count(u.id)')
                    ->where('u.statut IS NULL')
                    ->getQuery()->getSingleScalarResult()
            ;
    }

    /**
     * Liste des derniers inscrits
     * use DefaultController:backendAction
     */
    public function findLastUser($limit)
    {
        return $this->createQueryBuilder('u')
                    ->where('u.statut IS NULL')
                    ->orderBy('u.publieLe', 'DESC')
                    ->setFirstResult(0)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }
}
