<?php

namespace AppBundle\Repository;

/**
 * VillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillaRepository extends \Doctrine\ORM\EntityRepository
{
}
